[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.mypy]
files = "src,tests"

[tool.pytest.ini_options]
testpaths = ["tests"]
norecursedirs = ["tests/integration/hardware"]
